[tool.poetry]
name = "ktv"
version = "0.1.0"
description = "KTV create tool from Youtube"
authors = ["adason <tdadason@gmail.com>"]

[tool.poetry.dependencies]
python = "3.7"
youtube_dl = "^2020.1.1"
spleeter = "^1.4.9"

[tool.poetry.dev-dependencies]
pytest = "^5.3"